### ISSUE TITLE
[RouteControlOption] Value 가 1개씩 밀림

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#10]
API 문서는 이렇게 정의 되어 있음
 - 1: 티맵추천, 2: 최소시간, 3: 무료도로, 4. 최단거리, 5. 고속도로 우선, 6. 편한길 우선, 7. 어린이 보호
 -  아마 0부터 처리해서 그런지 해당값에 대해서 1개씩 밀려서 됨..

**Comment by aqkhsg** [comment]
소스 확인해보니 하나씩 밀리진 않고 1부터 맞게 되어있는데요.요청하는쪽 한번 확인 부탁드립니다.
참고로 어제 주신 vr테스트앱으로 제가 해보니 정상적으로 경로옵션에 맞게 동작 하는것같긴합니다.
그리고 한가지 ux 적인 내용인데, 경로 옵션 바꾸면 내비에서도 "최소시간 경로로 안내합니다" 가 나오는데 VR 앱에서도 "빠른길로 안내할게요" 를 안내해서 유사한 안내음성이 2번 나오고 있습니다. vr앱에서 음성안내 제외하는 방향으로 검토가 필요해보입니다.

**Comment by jhanulis7** [comment]
- VR 의 이슈입니다. 
> 면 내비에서도 "최소시간 경로로 안내합니다" 가 나오는데 VR 앱에서도 "빠른길로 안내할게요" 를 안내해서 유사한 안내음성이 2번 나오고 있습니다. vr앱에서 음성안내 제외하는 방향으로 검토가 필요해보입니다.

이건 전체적인 오디오 패스 확인을 이후에 할때 확인하겠습니다.!
