### ISSUE TITLE
최근기록 삭제 > 전체 선택> 1개가 항상 남음

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#12]
- [ ] 최근기록 삭제 > 전체 선택> 1개가 항상 남음
  - VR 이슈는 아닌데요, 최근목적지 다 지우고 테스트 해보기위해서 하는데 1개가 계속 남네요

**Comment by aqkhsg** [comment]
제가 해보니 최근기록 잘 삭제가 되는데요. 어떻게 삭제했는지 알 수 있을까요?

**Comment by jhanulis7** [comment]
터치로 진행한거고, 아래 영상 확인 부탁드립니다 - VR 연동 이슈보다는 최근목적지 개수 파악을 위해서 입니다.
[Screen_Recording_20210813-185328_TMAP AUTO.mp4.zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/6981518/Screen_Recording_20210813-185328_TMAP.AUTO.mp4.zip)

**Comment by aqkhsg** [comment]
13일 버전으로 영상과 같은 방법으로 여러번 테스트 해봤는데 재현이 안되네요.  특별한 재현케이스가 있는걸까요? 재현빈도도 궁굼하네요.

**Comment by jhanulis7** [comment]
금일 테스트 해도 동일합니다.  모든 최근기록 리스트는 VR 을 통해서 기록된 리스트입니다.
VR 앱으로 한번 2개정도만 목적지 선택 후, 리스트에서 전체 삭제를 해보시면 될거 같습니다. 백퍼 재현입니다.

**Comment by aqkhsg** [comment]
문제 현상 확인해서 수정하였고 26일 버전에서 확인 부타드립니다.

**Comment by jhanulis7** [comment]
08/30 test 버젼에서 최종 확인
