### ISSUE TITLE
ReqRouteOptionChange 콜백에  이전 경로대비 거리, 시간, 톨비 값 전달이 가능할가요?

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#17]
![image](https://user-images.githubusercontent.com/13480495/129658076-38bb6549-3f64-4c87-ad21-7799957ba5cc.png)

ReqRouteOptionChange 콜백에  아래와 같이 필드 전달이 가능할까요?

diffDistance :

<Value1 : Int>
routeOption
<Value2 : Int>
diffDuration : 기존 옵션대비 +- 값
<Value3 : Int>
diffDistance : 기존 옵션대비 +- 값
<Value4: Int>
duffTollFare (1700 으로 전달) : 기존 옵션대비 +- 값

**Comment by jhanulis7** [comment]
데이타 타입은 + - 정보가 있으니 아래와 같이 최종값으로 전달해주셔도 될것 같습니다.
![image](https://user-images.githubusercontent.com/13480495/129661977-e52faa5a-b34c-4c19-9e33-d21f418bcb84.png)

**Comment by aqkhsg** [comment]
vr앱이든 내비앱이든 어느쪽에서든 계산은 가능할것으로 보이는데요, 내비쪽 개발일정이 타이트 하고 VR에서만 표시하는 값인점에 따라 해당 계산은 VR쪽에서 처리해 주실 수 있으실까요?

**Comment by jhanulis7** [comment]
네 성민님, 내부에서 한번 해보는걸로 해볼게요..

**Comment by aqkhsg** [comment]
재희님. 제가 착각을 좀 했는데 주행시간 요금 +- 가 저희쪽 화면이었네요. 해당 정보 전달 가능할지 다시한번 검토해보고 말씀드리겠습니다.

**Comment by aqkhsg** [comment]
시간 + - 값,  요금 + -  전달 가능합니다. 문서에 업데이트 해주시면 맞춰서 전달 드릴게요.

**Comment by jhanulis7** [comment]
먼저 사내 로직부터 확인

**Comment by jhanulis7** [comment]
내부 로직으로 처리하겠습니다. 감사합니다.
