### ISSUE TITLE
경유지 1 설정 > 경유지 1 설정 > 기대치는 경유지 1이 2로 된뒤 2번째가 경유지 1이 되어야 함

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#18]
티맵
- 경유지 1 설정 > 경유지 1 설정 > 기대치는 경유지 1이 2로 된뒤 2번째가 경유지 1이 되어야 한다.
  - 어떻해 하면 될까요? 
      - 1안) 티맵이 같은 1이 오면 1이 2로 가고, 뒤에꺼가 1이 되게한다.
      - 2안) VR 이 경유지 1을 2로 한다음, 2번째 1을 추가
      - 3안) VR 이 Swap 을 한다음 1을 추가 (1개가 있어도)

**Comment by aqkhsg** [comment]
1안으로 하면 될것같습니다. 경유지가 2개 이미 있는 경우에는 경유지1로 또 내비에 요청이 오는 경우는 없다고 보면 되는거겠죠? vr앱에서 예외처리되는거겠죠?

**Comment by jhanulis7** [comment]
2개인 상황에서도
경유지 1로 추가를 하면, 
기존 경유지 1 -> 경유지 2로가고, 경유지2는 버림으로 가면 될것 같습니다.
> 경유지 2개인 상황(경유지 1: 강남역, 경유지2 신림역) > 서울역 경유지 추가 > 티맵에서 경유지1: 서울역, 경유지2 강남역 으로 변경

**Comment by jhanulis7** [comment]
경유지 삭제도 경유지 2개인경우, 경유지 1삭제시 경유지2가 경유지 1로 와야함
API v1.8 참조

**Comment by jhanulis7** [comment]
08/19 버젼에서 확인
