### ISSUE TITLE
[callback] 경로안내중 > "서울역" > onRouteEnd 가 항상 오지 않음

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#2]
버젼명 : 08/10 테스트앱 TmapAuto_TAXI_TestD1_0.0.2.1-2.apk
- [x] 경로안내중 > "서울역" > onRouteEnd 가 항상 오지 않음
  - 경로탐색중에 POI 검색하여 경로안내 시작하면, onRouteEnd 콜백이 안와서 시간정보 갱신이 안됨
    - 경로종료 후 진행하면 해당 콜백이 옴

**Comment by aqkhsg** [comment]
윤성민입니다.

**Comment by jhanulis7** [comment]
동작확인
