### ISSUE TITLE
 태블릿에서는 부산역해도 5초후 경로시작 잘 되는데, AVN 에서는 엄청 경로시작이 느림

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#21]
- [ ]  태블릿에서는 부산역해도 5초후 경로시작 잘 되는데, AVN 에서는 엄청 경로시작이 느림

**Comment by aqkhsg** [comment]
저희쪽 모트렉스 단말에 마이크가 없어서 바로 테스트가 어렵네요
테스트앱으로 reqRoute 부산역으로 요청해서 테스트 해보고 커멘트 하겠습니다.

**Comment by aqkhsg** [comment]
최신버전에서 강제로 reqRoute 날려봤을때 재현이 안되고 있는데, 혹시 최신버전에서도 재현 되나요?

**Comment by jhanulis7** [comment]
현재 비젼에서는 안나오고 있는데요 ,최종 확인해보겠습니다.

**Comment by jhanulis7** [comment]
다시 한번 확인 해보겠습니다!

**Comment by jhanulis7** [comment]
08/30 test 버젼에서 최종 확인
