### ISSUE TITLE
[Navigation][pre-QA] 하이패스 사용자에게 묻는 팝업에서의 VR 스펙 결정 #261

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#28]
![image](https://user-images.githubusercontent.com/13480495/130577060-be7f11ca-3928-48cd-ace7-2bbeba2619b1.png)

**Comment by jhanulis7** [comment]
하이패스 스펙결정에 따라 진행 예정, 현재는 재현됨

**Comment by MjayP** [comment]
@aqkhsg 
하이패스 설정 Default값이 OFF로 됨에 따라, 위 팝업은 표시되지 않을 것 같습니다. 확인 부탁드립니다. 
<img width="838" alt="image" src="https://user-images.githubusercontent.com/50140918/132145749-a89c0723-2fda-47e8-bb6b-6c45f8ad57cb.png">

**Comment by aqkhsg** [comment]
9/10 버전에서 확인 부탁드립니다.

**Comment by jhanulis7** [comment]
09/11 티맵 test 버젼 정상 동작확인(하이패스 팝업 없음)
