### ISSUE TITLE
[Navigation][pre-QA] 티맵 이어받기 팝업에서 VR 실행

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#29]
![image](https://user-images.githubusercontent.com/13480495/130577128-6d3bfac6-f874-4adb-81aa-80e00e77251e.png)

**Comment by jhanulis7** [comment]
최신 릴리즈버젼에도 재현됨

**Comment by MjayP** [comment]
티맵 UX측에서 아래 내용으로 검토 진행 중

> 티맵 팝업이 생성되어 있는 상태 > 내비 관련 발화로 showCurr API 호출 > 티맵에서 이 API 를 받으면 기본 화면이 아닌 작업이면 모두 취소하고 이후 명령을 수행 (협의 완료)
> 단, 마지막 부분 티맵이 API를 받을 때 ‘팝업 별 닫힘 정책’은 티맵UX 정책 참고 (티맵 검토중)

**Comment by jhanulis7** [comment]
09/11 티맵 test 버젼 정상 동작확인
