### ISSUE TITLE
서울역 > 추천경로 안내중 > 무료도로 바꿔줘 > 경로변경 콜백 > 목적지에 값 읽음 > 추천경로 데이타가 남아 있음 > 이후 값 바뀜

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#33]
- [x] 서울역 > 추천경로 안내중 > 무료도로 바꿔줘 > 경로변경 콜백 > 목적지에 값 읽음 > 추천경로 데이타가 남아 있음 > 이후 값 바뀜
  - onRouteOptionChanged 콜백이 목적지 정보값 갱신후 콜백이 와야 할 것으로 보임

**Comment by jhanulis7** [comment]
destination_table 든 waypoint_table 든 다 업데이트 이후에 onRouteOptionChanged 보내는것으로 협의

**Comment by aqkhsg** [comment]
9/2  버전에 전달드리겠습니다.

**Comment by jhanulis7** [comment]
08/30 test 버젼에서 최종 확인
