### ISSUE TITLE
reqWayPointChange 콜백에서 Value2 필드 추가

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#35]
- [x] reqWayPointChange 콜백에서 Value2 필드 추가
![image](https://user-images.githubusercontent.com/13480495/130755689-494b76f2-7a73-4293-85a0-83923a9d0cd6.png)

**Comment by aqkhsg** [comment]
9/2  버전에 전달드리겠습니다.

**Comment by jhanulis7** [comment]
08/30 test 버젼에서 최종 확인
