### ISSUE TITLE
[Navigation][pre-QA] 도착지까지 도달할려면 충전이 필요합니다. 팝업 > 취소 안됨 Navigation TMap UX

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#37]
- [ ] 도착지까지 도달할려면 충전이 필요합니다. 팝업 > 취소 안됨 Navigation TMap UX
![image](https://user-images.githubusercontent.com/13480495/130897855-59e6cfb3-5b7d-40bd-ba74-fef05d8ad582.png)
![image](https://user-images.githubusercontent.com/13480495/130897863-600fc6e8-3a4b-494e-bb9d-395202373222.png)

**Comment by jhanulis7** [comment]
넵!
도일 처리 완료되었다고 코멘트 남겨주시면 확인 후 클로스하겠습니다

**Comment by aqkhsg** [comment]
9/10 버전에서 확인 부탁드립니다.

**Comment by jhanulis7** [comment]
9/10 버젼 동작 확인
