### ISSUE TITLE
터치로 우리집 등록 > vr 로 우리집으로 안내해줘 > 이후 티맵 앱 죽음

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#41]
> 터치로 우리집 등록 > vr 로 우리집으로 안내해줘 > 이후 티맵 앱 죽음
> 터치로 회사 등록 > vr 로 회사으로 안내해줘 > 이후 티맵 앱 죽음

![image](https://user-images.githubusercontent.com/13480495/131464936-1d76db8f-a2ae-4b20-8ad5-f7fc07e7d3dd.png)

**Comment by jhanulis7** [comment]
9/1 제공앱에서는 재현되지 않음

**Comment by aqkhsg** [comment]
9/10 버전에서 확인 부탁드립니다.

**Comment by jhanulis7** [comment]
9/10 티맵 테스트 버젼 동작 확인
