### ISSUE TITLE
VR에서 전체 경로 화면 요청 시, 화면 좌측 상세 경로 정보 UI를 hide

### ISSUE THREAD

**Issue by huthuthut** [hkmc-airlab/pbv_client_tmap#42]
![스크린샷 2021-09-01 오전 10 14 34](https://user-images.githubusercontent.com/60503515/131615164-e758bef3-6daa-49cf-93da-2d67fe3387e5.png)

첨부한 이미지와 같이 전체 경로 화면 요청 시 좌측 상세 경로 정보 UI를 hide 하고 싶습니다.
조금 더 구체적으로 말씀 드리자면,

- 기존 티맵 터치로 호출하는 ‘전체 경로 화면‘(좌측 UI 포함)은 유지
- VR에서 호출하는 ‘전체 경로 화면’에서는 좌측 상세 경로 UI를 hide
- 그렇게 제공해 주시면 VR에서는 저희가 만든 경로 정보를 띄울 예정입니다.

그렇게 만들어져서 기대하는 VR에서의 전체 경로 화면은 첨부한 이미지와 같습니다.

![pbv_Navi Test_1](https://user-images.githubusercontent.com/60503515/131615315-0205f3fa-80b1-4d13-abf3-0587fe3da1e6.png)

**Comment by aqkhsg** [comment]
9/10 버전에서 확인 부탁드립니다.

**Comment by jhanulis7** [comment]
![image](https://user-images.githubusercontent.com/13480495/133020385-fe620a4e-9fa0-46ee-8076-6af60cac2791.png)
동작확인완료

**Comment by jhanulis7** [comment]
패널이 없어짐을 9/10 버젼에서 확인
