### ISSUE TITLE
[개발 확인 요청] Road Event 시, Agent Hide 요청 적용 여부 

### ISSUE THREAD

**Issue by MjayP** [hkmc-airlab/pbv_client_tmap#43]
스펙 내용 : 중요 유고 팝업 발생 시, 티맵에서 Agent Hide 되도록 이벤트 전달하여 에이전트 강제 종료

![image](https://user-images.githubusercontent.com/50140918/131615522-ae912727-c1fb-490e-bd4b-bce23f7059f2.png)

위 스펙 개발 적용 여부 확인 부탁드립니다.

**Comment by aqkhsg** [comment]
9/10 버전에서 확인부탁드립니다.

**Comment by jhanulis7** [comment]
![image](https://user-images.githubusercontent.com/13480495/133020672-75ff4eff-bf8e-4a24-b6bf-52e941d6699b.png)
동작확인
