### ISSUE TITLE
[개발 확인 요청] 배터리 부족 팝업, 목적지 도달 시 배터리 부족 팝업 삭제

### ISSUE THREAD

**Issue by MjayP** [hkmc-airlab/pbv_client_tmap#44]
- 배터리 부족 팝업 -> 삭제. 시스템 경고 및 에이전트 경고로 대체
- 목적지 도달 시 배터리 부족 팝업 (Auto Adding Off 팝업) -> 삭제
- 목적지 도달 시 배터리 부족 팝업 (Auto Adding On 팝업) -> 삭제

![image](https://user-images.githubusercontent.com/50140918/131615789-a3beb9eb-039e-43d0-8a9a-f835aa022b14.png)

- Auto Adding 기능 및 스펙 -> 삭제 (요청 주최 : TaaS 최병휘 매니저). 어느 범위까지 삭제하는지는 요청 주최 측에 확인 필요

**Comment by jhanulis7** [comment]
@aqkhsg 님, 스펙 협의가 필요하시면  UX 분들 계정주시면 등록 해드리겠습니다.

**Comment by aqkhsg** [comment]
이 팝업은 삭제 하기로 지난번에 협의되어서 삭제될 예정입니다.

**Comment by jhanulis7** [comment]
@aqkhsg 님, 
모든 리스트에 마일스톤 일정을 제가 먼저 작성했는데요, 리뷰 부탁드립니다.

**Comment by aqkhsg** [comment]
9/10 버전에서 확인 부탁드립니다.

**Comment by jhanulis7** [comment]
확인 완료
