### ISSUE TITLE
[Navigation] 티맵 도착지 팝업시 VR 실행 > 서울역 리스트 화면시 hide 안됨 

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#46]
- [x] 티맵 도착지 팝업시 VR 실행 > 서울역 리스트 화면시 hide 안됨 

![image](https://user-images.githubusercontent.com/13480495/131623406-2cdaf741-c2d7-4583-a3d3-fd1122b6161c.png)

**Comment by jhanulis7** [comment]
[Navigation] 티맵 도착지 팝업시 VR 실행시 > 서울역 리스트 화면 > hide 안됨
![image](https://user-images.githubusercontent.com/13480495/132215132-c4f16ba3-d904-40d1-99d6-5e27cedbe523.png)

**Comment by aqkhsg** [comment]
해당 내용은 9/9 버전에 포함될 예정입니다. 해당 버전으로 확인 부탁드리겠습니다.

**Comment by jhanulis7** [comment]
확인완료
