### ISSUE TITLE
경탐 진행중에 VR 통해서 새로운 목적지로 경탐 요청시 오동작 됨

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#47]
Confirm 화면에서 "그래" 발화 후 Thinking 일때 ptt 로 다시 Listening 진입 하여 "우리집" 발화 했을 때
Chrome Listening 화면으로 전환 되고, confirm 그래 취소 , 우리집 으로 경로 설정 되어야 함.
https://cody-ims.autoever.com/browse/PBV01QA-36

[이슈 현상]
POI "중계역 3번출구" 발화 하여 안내 하려는 도중 "우리집" 발화 시 "우리집으로 안내할게요" TTS 발생, 전체경로 확인시 처음 발화한 중계역 3번출구 안내 하는 현상

[사전 조건]

우리집 즐겨찾기 되있는 상태 (ex. 부산역)
[재현 스텝]

"중계역 3번출구" 안내 > 그래 버튼 선택 > "중계역 3번출구로 안내할게요" 음성 나오는 중간에 > 음성 버튼 선택 > "우리집" 발화 > 전체경로 확인
[기대 결과]
전체 경로확인시 우리집으로 길안내 해야함

![image](https://user-images.githubusercontent.com/13480495/131949325-fcacd767-8c66-4ebc-9996-6c1daf3dbb10.png)

저희가 경탐 진행중에 VR. 통해서 다른 목적지로 requestRoute 를 하면 이전 경탐진행중을 취소하고, 새롭게 경탐 진행이 가능할까요?
티맵 터치로는 막혀있긴 하던데요..
검토 부탁드립니다.

**Comment by aqkhsg** [comment]
@jhanulis7  님
전체경로화면에서 타이머로 동작 되고있는데요, 타이머 중간에 기존경로 취소하는 시나리오가 기존에 없던 시나리오여서 화면이 꼬이거나 하는 사이드가 많이 예상됩니다. 해당 내용은 지원이 어려울것같습니다.   vr앱에서 ux적으로 풀어주시는게 좋을것같습니다.

**Comment by jhanulis7** [comment]
@aqkhsg 넵, 알겠습니다
내일 회의때 저희가 OSD API 를 받아서 예외처리를 할 수 있는지 문의 해보겠습니다.

**Comment by jhanulis7** [comment]
- VR에서 requestRoute - onRouteEnd 사이에 request 오면, 사용할 수 없도록 처리 예정, 이슈 클로스 하겠습니다.
