### ISSUE TITLE
[Navigation] 경탐 시작 시 전체 경로 화면 노출 시간 조정하고, 경탐 시점에 내비 도메인 발화를 막는 이슈

### ISSUE THREAD

**Issue by huthuthut** [hkmc-airlab/pbv_client_tmap#48]
이슈  :  경탐 시작 시 전체 경로 화면 노출 시간을 조정하고, 경탐 시점에 내비 도메인 발화를 막는 이슈입니다.
내용  :  
    - 티맵에 전체경로 노출 시간을 영상으로 요청하였고, 확인 후 3초가 적절하다고 판단했습니다
    - 티맵에는 3초 변경을 요청한 상태입니다
    - 이후 논의가 필요한 부분은 경탐 중간에 내비 도메인 발화가 추가로 들어가지 않도록 구현 부분입니다.

**Comment by huthuthut** [comment]
참고로 티맵에서 받은 1,2,3,4초 영상을 공유 드립니다.

https://user-images.githubusercontent.com/60503515/132625348-edb45d3f-81fd-412a-8277-3576ded0b4df.mp4

https://user-images.githubusercontent.com/60503515/132625335-6a9e55d3-8af4-4e31-9ec2-69f6f361688d.mp4

https://user-images.githubusercontent.com/60503515/132625323-7c0a486c-1c2c-4ada-9ad8-ecf92c4ebfd4.mp4

https://user-images.githubusercontent.com/60503515/132625388-0e33d33b-e577-4be1-ab16-d9a6ee017df5.mp4

**Comment by aqkhsg** [comment]
3초로 적용하겠습니다.

**Comment by jhanulis7** [comment]
3초 적용 확인

**Comment by jhanulis7** [comment]
- 경로탐색 후 전체경로 보여주는 시간 : 3초로 변경
- "전체경로 보여줘" 했을때 전체경로 보여주는 시간 : 5초 

UX 에서 이렇게 요청이 왔고, 위 3초 영상을 보고 의사결정이 되었습니다.

cc @huthuthut

**Comment by aqkhsg** [comment]
네. 아래와 같이 적용하겠습니다.
경로탐색 후 전체경로 보여주는 시간 : 3초
"전체경로 보여줘" 했을때 전체경로 보여주는 시간 : 5초

**Comment by aqkhsg** [comment]
9/23버전에 수정되었습니다.

**Comment by jhanulis7** [comment]
- 9/23 확인, 이슈 클로스
