### ISSUE TITLE
[Navigatioin] 약관 API 

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#49]
AS-IS : 
![image](https://user-images.githubusercontent.com/13480495/132679624-597797f6-625a-4dad-a43f-6efe450e6cdb.png)
위와 같이 설계 진행하였으나, 티맵에서 약관 처리 로직이, 티맵 엔진들이 초기화가 되기전에 shared preference 에 저장처리를 하므로,
기존 설계 state table Content Provider 로 제공이 어려움
 - 제안1) state table 이 없으면 약관 미동의로 처리하면 어떤가?
 
TO-BE : 
제안1) 처럼 했을때 약관 철회를 하는 경우, state table 은 계속 남아 있기 때문에 해당 제안 방식은 사용하기 어려울것으로 봄

대안1) SharedPreference. 앱간의 데이타 공유 방식 이용 - API 17 부터 deprecated 되어서, develop guide 에서 Content Provider. 권장
<img width="1530" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/13480495/132680433-bedb9ff4-67e9-4e30-9bc4-6bde39ad48b8.png">

대안2) 별도의 terms table 을 내비엔진이 초기화가 되지 않았다하더라도 , 약관로직에서 Content Provider 로 제공하는것이 제일 좋은 방법이라고 판단됨.

@aqkhsg 님, 생각을 좀 해봤는데요,
대안2 처럼, 약관 처리 로직에서 Content Provider 를 별도의 table 로 제공해주는것이 좋을거 같습니다. 아니면 기존 state table 에 필드 추가 하는 방식으로로 하거나요..

검토 부탁드립니다.

## 기본 시나리요
티맵앱 실행 1회 이상 > APP Terrm API > access 실패 > 사용자에게 약관 동의 팝업
티맵앱 실행 1회 이상 > APP Terrm API  > access 성공 > terms 선택에 따라서 약관 동의 팝업 또는 티맵 서비스 제공
티맵앱 실행 0회 > 사용자에게 약관 동의 팝업
티맵앱 실행 1회 이상 > APP Terrm API  > access 성공 > 약관 동의 > 티맵 서비스 제공 > 약관 철회 > 사용자에게 약관 동의 팝업 제공 <--- 제안1 은 여기에 이슈 발생됨

**Comment by jhanulis7** [comment]
9/20 아래와 같이 기존 API 설계 사양으로 진행하기로 결정

![image](https://user-images.githubusercontent.com/13480495/132782502-a630a934-9b33-4f9e-8735-01b73d56e731.png)

**Comment by aqkhsg** [comment]
완료되면 말씀드리겠습니다.

**Comment by huthuthut** [comment]
@aqkhsg 님, 안녕하세요. AIRS의 김정도 책임 연구원입니다.
약관 관련 궁금한 것이 있어서 여기에서 문의 드립니다.
---------------------------
1. 약관 미동의 상태에서 VR에서 티맵 기능을 요청하면, 티맵에서는 자동으로 약관 동의 설정 화면의 띄워주나요?
2. 만일 자동으로 약관 동의 설정 화면을 띄워준다면, 아래와 같은 케이스에서도 자동으로 약관 동의 설정 화면을 띄워주는지 알고 싶습니다.
     -  티맵 약관 동의 해서 티맵 잘 사용하다가, 설정차에서 티맵 약관을 철회 한 이후, VR로 내비게이션 관련 발화 (티맵 기능 요청)한 경우

**Comment by jhanulis7** [comment]
09/11 티맵 test 버젼 정상 동작확인
@huthuthut 문의 후 close 예정

**Comment by aqkhsg** [comment]
1. 약관 미동의 상태일때 티맵을 포어그라운드로 실행시킨다면 팝업이 떠있는 상태일 겁니다.
2. 약관 미동의 상태일때는 내비가 동작 안하기 때문에 콘텐트프로바이더의 값(목적지 경유지 정보나, 내비 상태 값들 ) 이 제대로 안들어있을 것이고, 내비 관련 콜백들도 당연히 전달이 안될겁니다.
