### ISSUE TITLE
VR 종료 후, 다음 길안내부터 TTS 제공 

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#50]
![image](https://user-images.githubusercontent.com/13480495/133059748-49314ba7-812c-4fdd-8e76-7210ee6c5fdc.png)

모트렉스와 협의해야 할 이슈같아 보이는데요?

**Comment by MjayP** [comment]
@aqkhsg 성민님, '내비 길 안내 목소리가 나오는 중', '내비 과속 경고음 중' 음성 인식 시작 시, 위 스펙으로 개발 가능한지 검토 요청드립니다.

**Comment by aqkhsg** [comment]
길안내랑 경고음을 따로 나눈 이유는 vr음성 끝나고 다시 내비로 오디오 포커스 왔을때 경고음은 바로 다시 나와야되서 나눠진게 맞을까요? 경고음을 1초마다 생성하고 있어서 아마 바로 나올것 같긴 한데요. 관련해서 혹시 테스트 해볼 수 있을까요?

**Comment by MjayP** [comment]
@aqkhsg 성민님 두개를 나눈 이유는 말씀하신 목적이 맞습니다. (경고음은 꺼지면 안되니까요;; ㅋㅋ)
@jhanulis7 재희님 혹시 set에서 확인 가능하실까요?

**Comment by jhanulis7** [comment]
@MjayP  님,

현재 오디오는 시스템 설정 전입니다.  모트렉스 가이드가 전달 되어 구현 이후 확인이 가능합니다.
해당 이슈는 계속 keep 예정입니다.

**Comment by jhanulis7** [comment]
모트렉스 시스템에서 진행하므로, 해당 이슈는 티맵에서 클로스 하겠습니다.
