### ISSUE TITLE
 티맵 콜백이 오지 않으면, 에이전트 화면 유지, 더이상 티맵 요청을 할 수 없는 상태

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#53]
서울역 > 첫번째 > requestRoute > 아래와 같이 충전관련 팝박스 > VR에게 ReqError 를 전달 해야 함
![image](https://user-images.githubusercontent.com/13480495/134887386-bbe7925a-af0d-42df-b2b6-4f0aa59cc166.png)

**Comment by aqkhsg** [comment]
해당 팝업 뜰때 reqError 콜백 보내도록 처리하였습니다. 값은  (ERROR_LOW_BATTERY = 1) 로 전달 하겠습니다.

**Comment by aqkhsg** [comment]
9/29 버전에 적용되었습니다.
