### ISSUE TITLE
티맵 약관 동의완료 > 티맵 프로세스 죽임 > 티맵약관 비동의로 전달됨

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#55]
![image](https://user-images.githubusercontent.com/13480495/135002060-5845495e-6787-472a-85ac-6fc2a4e4f903.png)

**Comment by jhanulis7** [comment]
최초 부팅 후 티맵을 한번도 실행 안한 경우,
티맵이 크래쉬가 나서 종료된 경우 발생이 됩니다. 
티맵이 실행이 안된 상황에서도 약관 정보를 제공해줄수 있는지에 대한 여부 내부 검토후 전달 받기로 함
현재 VR은, 서울역(내비) 발화 하여 도메인이 내비이면 티맵을 실행시키기 때문에, 이미 그전에 DM 에 전달할 약관정보가 필요하기 때문에 ,
routeOption -1 값을 받아서 다시 읽더라도 동일하게 디폴트값을 받을것 같습니다. 
확인 부탁드립니다.

**Comment by aqkhsg** [comment]
약관 동의 여부 값은 정상값으로 채워서 전달하도록 수정하였습니다.
9/29 버전에 적용되었습니다.

**Comment by jhanulis7** [comment]
확인완료
