### ISSUE TITLE
[callback]  최근목적지보여줘 > 경로리스트 >  선택 > 길안내 > 용산역 > 리스트  > 선택 >  onWayPointChagned 콜백옴

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#6]
- [ ] 서울역 > 경로리스트 >  선택 > 길안내 > 용산역 > 리스트  > 선택 >  onWayPointChagned 콜백옴
  - 목적지 변경이므로 onGoalInfoChanged가 와야 할거 같으나, onWayPointChagned 콜백이 옴
  - 맵상으로도 경유지 추가 안되어 있음

**Comment by aqkhsg** [comment]
최근목적지 보여줘 > 리스트 중 용산역 선택 > 내비 화면 상 목적지는 용산역으로 변경 되었는데, onWayPointChagned 콜백이 전달되었다는 얘기가 맞나요?

**Comment by aqkhsg** [comment]
용산역으로 목적지 선택할때는 reqRoute 로 요청한걸까요?

**Comment by jhanulis7** [comment]
네,
>최근목적지 보여줘 > 리스트 중 용산역 선택 > 내비 화면 상 목적지는 용산역으로 변경 되었는데, onWayPointChagned 콜백이 전달되었다는 얘기가 맞나요?
맞습니다.
reqRoute 임에도 그렇게 콜백이 오고 있습니다

**Comment by aqkhsg** [comment]
확인 해서 수정했고 8/13일 배포에 수정된내용 포함해서 배포하겠습니다.
