### ISSUE TITLE
[Navigation] 티맵 약관동의 > 티맵 정상 동작 수행 > 티맵 환경설정 초기화 > VR 약관 미동의 상태로 전달되나 티맵은 동작됨 #641

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#62]
[Navigation] 티맵 약관동의 > 티맵 정상 동작 수행 > 티맵 환경설정 초기화 > VR 약관 미동의 상태로 전달되나 티맵은 동작됨 
  - 2로 전달됨
![image](https://user-images.githubusercontent.com/13480495/140014754-43ed67b9-2814-4833-a02a-052788aeee68.png)

**Comment by aqkhsg** [comment]
![image](https://user-images.githubusercontent.com/42509008/140028213-1af22ccb-769e-4975-9a85-8115c8eacb31.png)

설정 초기화가 저 이미지속 버튼 맞을까요? 테스트해보니 정상적으로 1로 전달하고 있어서요.

**Comment by jhanulis7** [comment]
11/5 테스트앱 정상동작 확인
