### ISSUE TITLE
목적지까지의 충전값이 오른쪽 상단값(VR값) 과, 티맵 패널에서 나오는 값이 다름

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#63]
- 목적지까지의 충전값이 오른쪽 상단값(VR값) 과, 티맵 패널에서 나오는 값이 다름
  - ![image](https://user-images.githubusercontent.com/13480495/140487866-b87ab89e-327e-41a5-b209-c6a6768fab33.png)
  - ![image](https://user-images.githubusercontent.com/13480495/140487905-78f45b10-9356-4506-988f-eb8161aedba0.png)
- EV Test Layer current level 이 , 목적지까지의 충전값으로 설정됨.

**Comment by aqkhsg** [comment]
@jhanulis7 VR에서 탐색 요청했을 시에만 에러코드 콜백을 보내고 있습니다.
터치시에는 팝업으로 내용을 표시하고 있어서 따로 에러코드를 보내고있지는 않습니다.

**Comment by jhanulis7** [comment]
티맵 v0.6.3 적용

- 우측상단, 티맵패널, VR패널 충전값 동일 확인
