### ISSUE TITLE
터치로 부산역 경유지 추가 중 VR 동작하면 TMAP/VR 오류 발생

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#64]
- 터치로 부산역 경유지 추가 중 VR 동작하면 TMAP/VR 오류 발생
- VR 이 터치로 경탐진행하는 동안을 알 수 없어서 터치 경탐중에 VR API 호출하게 됨
- 이를 해결하기 위해서, state table 에 아래와 같이 필드 추가 
- requestRouteOn  1: Active(경탐중..경로변경중.. API 를 받을수 없는 상태), 2: Ready

![image](https://user-images.githubusercontent.com/13480495/140490100-129c2607-69f5-428d-a62c-a64d9c338854.png)

**Comment by aqkhsg** [comment]
state table에 추가 하도록 하겠습니다.  requestRouteOn 1: Active(경탐중..경로변경중.. API 를 받을수 없는 상태), 2: Ready

**Comment by jhanulis7** [comment]
@aqkhsg 님
테스트 해본 결과,  아래 시나리오에 대해서만 처리 되면 안정적인 VR<->TMap Sync 가 이루어질거 같습니다.
- 터치로 서울역 선택 > 타이머 동작중 > VR > 다른경로 > 타이머종료 상위 화면상태 임 > 에이전트 콜백 기다리나 콜백 안옴

제 생각에는 아래와 같이 다른경로를 선택했을때, 실제적으로 전체경로 화면에서 경로옵션을 바꾸어지면 좋을것 같습니다. 이미 좌측 패널에서 터치로 하면 전체경로 화면에서 경로가 바뀌고 있어서, requesReRoute 등 저희 API 가 동작이 되면 깔금해질거 같습니다. (active coverage 를 넓힐 필요없이)


![image](https://user-images.githubusercontent.com/13480495/140724049-cd901b75-3863-4ae2-9798-c183fcf789bc.png)

**Comment by jhanulis7** [comment]
- 11/09 테스트 버젼으로 확인. 해당 스펙으로 다음 배포 부탁드립니다. 이슈 클로스 합니다.
