### ISSUE TITLE
1000km 경탐 실패 팝업 처리를 위한 API 로직

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#65]
1. VR 1000km 이상 설정으로 목적지/경유지 설정
리스트 화면에서 하나를 선택하거나 컨펌 화면에서 "그래" 발화를 함
2. DM to VR. : requestRoute
3. VR to TMap : requestRoute
4. TMap : 경로계산중 1000km 이상이면 - 티맵 오류 팝업 제거 (VR시에만, 터치진입은 유지)
5. TMap to VR 에러전달
 - reqError
6. VR to DM 으로 에러 전달 (이벤트정의) 
7. DM to VR 로 display+tts
“1000km 이하 경로만 안내 가능합니다”

![image](https://user-images.githubusercontent.com/13480495/140489747-f719893f-7fae-4b3a-8b40-c9849b6d8f1a.png)

**Comment by jhanulis7** [comment]
금일 오전에 티맵 서버가 잠시 먹통이 된적이 있었는데요, 경탐시 그때 토스트로 서버와 어쩌구 연결할수 없습니다. 토스트가 나왔지만 저희쪽으로 넘어오는 로그는 없었던거 같습니다.

**Comment by aqkhsg** [comment]
네 추가로 확인해보겠습니다.

**Comment by aqkhsg** [comment]
@jhanulis7 님
서버 에러 인경우 3으로 전달 주신다고 하셨는데요, 실제적으로 경유지 추가시 위 이미지와 동일한 에러가 빈번히 나오는데요. 이 때 에러값이 전달 되지 않습니다.
실제적으로 목적지/경유지 Cancel 이 된건지, 저화면에서 나가면 모든 안전운행으로 되어 있습니다. 서버에러인지, 그 전에 에러 발생으로 전달이 안된건지 모르겠네요
  --> 이런 팝업이 뜰때 어떤식으로 테스트 하신건지 알 수 있을까요? 터치로 경유지 선택했을때 저런현상이 나타나나요?


금일 오전에 티맵 서버가 잠시 먹통이 된적이 있었는데요, 경탐시 그때 토스트로 서버와 어쩌구 연결할수 없습니다. 토스트가 나왔지만 저희쪽으로 넘어오는 로그는 없었던거 같습니다.
  --> 이때는 터치로 테스트하신건지 VR로 요청하신건지 확인 부탁드립니다.

**Comment by jhanulis7** [comment]
@aqkhsg 님
상위 두가지 케이스 모두 터이로 했을때 발생이 되었습니다.
그래서 실제적으로 3 으로 전달되는 코드가 들어가 있는지 확인이 필요해보였습니다.
특히 2번째 경우는 실제 서버의 이슈로 약 5-10분정도 무저건 실패였습니다.
토스트도 나왔던걸로 기억이 납니다

**Comment by aqkhsg** [comment]
@jhanulis7  VR에서 탐색 요청했을 시에만 에러코드 콜백을 보내고 있습니다.
터치시에는 팝업으로 내용을 표시하고 있어서 따로 에러코드를 보내고있지는 않습니다.

**Comment by jhanulis7** [comment]
에러값이 오는경우 확인
