### ISSUE TITLE
VR 독도 목적지 설정 > VR 목적지 주변 충전소 > 세번째 > 티맵 크래쉬후 재실행

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#66]
VR 독도 목적지 설정 > VR 목적지 주변 충전소 > 세번째 > 티맵 크래쉬후 재실행

버젼 0.4.5.1(테스트 버젼)에서 위와 같이 발생이 되고,

- 정식버젼은 아래와 같이 된다고 모트렉스 qa 이슈  올라옴

[빌드 버전]

QA 0.5.0
[테스트 환경 정보]
Mobile - Device : AVN

[발생 빈도]
10/10

[이슈 현상]
목적지 주변에 없는 카테고리를 위해 POI 를 독도로 설정 후 "목적지 주변 충전소" 발화하여 2개의 경유지 추가 동작시 두번째 경유지 추가 안되는 현상

[사전 조건]
1.POI "독도"로 설정 된 상태

[재현 스텝]
1. "목적지 주변 충선소" 발화 > "목적지 주변

{충전소}를 찾지 못했어요. 근처 {충전소}

중 몇 번째로 갈까요?" TTS 발생 > "네번째"발화 하여 경유지 추가 완료
2. "목적지 주변 충선소" 재발화 > "목적지 주변

{충전소}를 찾지 못했어요. 근처 {충전소}

중 몇 번째로 갈까요?" TTS 발생도중 > 리스트 번호 (ex.3번) 선택

[기대 결과]
경유지로 추가 되어야함

[기타 참고사항]

**Comment by aqkhsg** [comment]
레드마인 이슈로 보이는데 몇번이슈인지 알수있을까요?

**Comment by jhanulis7** [comment]
@aqkhsg 님

해당 이슈 2개가 있는데요

1번째는 테스트 버젼으로 주시는 경우 모두 로그 드렷듯이 크래쉬가 발생합니다.
2번째는 경유지가 추가가 안된다라는 이슈로 저희 VR 의 이슈인지 확인해봤는데요,
해당 배포된 공식버젼 v0.5.0 으로 해보니 100% 재현이 됩니다.
즉 크래쉬가 나지는 않고 2번째 경유지 추가시 콜백이 안와서 timeout 처리를 했구요
그 다음 VR PTT 누르고 나면, 경유지가 1개만 저장이 되어 있고, 
경로상엔 1, 2번 경유지 마커가 보입니다.

크래쉬 1번이 해결되면 되는것인지, 버젼 0.5.0 으로 확인 부탁드립니다.

**Comment by aqkhsg** [comment]
어제 정식 배포한 버전(0.6.1) 에 수정하였습니다. 확인 부탁드립니다

**Comment by jhanulis7** [comment]
- 정식 버젼 0.6.1 AVN 에서 재현 안됨 확인하여 이슈 클로스 합니다.
