### ISSUE TITLE
오류가 발생시, 티맵은 경로종료가 되는데, isRouteOn 은 경로안내중으로 전달 됨

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#67]
routingOn = 1 이어서 경로안내중으로 전달되어 경로가 없는데도 VR 이 전체경로 보여줘 등 경로가 있는 시나리오가 수행이 되어 오류가 발생이 됨

getNaviState: State(routingOn=1, routeOption=1, remainDestinationChargingInt=0, remainWaypoint1ChargingInt=0, remainWaypoint2ChargingInt=0, trafficStatus=교통 상황을 화면에서 확인해주세요., termsPermission=1, initComplete=2, requestRouteOn=2)

**Comment by jhanulis7** [comment]
재현경로
- 터치 부산역 목적지 > 터치 서울역 경유지 추가 > 안내 버튼 타이머 상태 > VR 다른경로 > 첫번째 > 티맵 오류 발생 >. onRouteCancel 콜백옴 
- 콜백에서 저희가 처리하더라도, VR 버튼 누를때 state table 을 읽어서 구성하는데 그때 routingOn 이 경탐중이라고 다시 셋팅이 됩니다.

**Comment by aqkhsg** [comment]
수정완료 했습니다. 배포 일정 잡히면 커멘트 달겠습니다.

**Comment by jhanulis7** [comment]
티맵 v0.6.3 CurrentDestionation DB 갱신되는것을 확인
