### ISSUE TITLE
[Navigation] VR/Touch 서울역 > 안내중 > 터치 부산역 > 부산역 티맵 패널 화면 > 타이머 동작중 > 백키 > 백키 > 안내종료 #670

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#71]
- [ ] VR/Touch 서울역 > 안내중 > 터치 부산역 > 부산역 티맵 패널 화면 > 타이머 동작중 > 백키 > 백키 > 안내종료 > CurrentDestionation DB 계속 남아 있고 isRoutingOn 경로중이라고 남음
- 연관 이슈 : https://github.com/hkmc-airlab/pbv_client_tmap/issues/67
- 
- getNaviDestination: Destination(name=서울역, address=서울 용산구 한강대로 405, totalDistance=20740, totalTime=2580, longitude=126.96924635573579, latitude=37.55311351429955, tollFare=0, poiId=219821)

- getNaviState: State(routingOn=1, routeOption=1, remainDestinationChargingInt=0, remainWaypoint1ChargingInt=0, remainWaypoint2ChargingInt=0, trafficStatus=교통 상황을 화면에서 확인해주세요., termsPermission=1, initComplete=2, requestRouteOn=2)

**Comment by jhanulis7** [comment]
- 정식 버젼 0.6.1 AVN 에서 동일 이슈 재현됨

**Comment by aqkhsg** [comment]
수정완료 했습니다. 배포 일정 잡히면 커멘트 달겠습니다.

**Comment by jhanulis7** [comment]
티맵 v0.6.3 CurrentDestionation DB 갱신되는것을 확인
