### ISSUE TITLE
[Navigation][기능] “도착 예정 시간” 발화 시 티맵 화면에 나오는 시간과 VR 안내 값이 상이한 현상

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#72]
[테스트 환경 정보]
Mobile - Device : AVN 재현됨

[발생 빈도]
10/10

[이슈 현상]
“도착 예정 시간” 발화 시 티맵 화면에 나오는 시간과 VR 안내 값이 상이함

[사전조건]

[재현경로]

*test 시작 시간 : 오전 11시 21분(AVN 기준)
1. "용산역으로 안내해줘" 발화 > "용산역(4.5km)" 선택 > 오전 11시 40분 도착 예정 TTS 송출
2. 봉화역(171.4km)으로 경유지 추가 > 오후 2시 36분 도착 예정 TTS 송출
3. 스타벅스 경유지 추가 > "스타벅스 을지로국제빌딩점(253m)" 선택해 경유지 추가
4. "얼마나 걸려" 발화 > 경유지 1번(스타벅스 을지로국제빌딩점) 도착 예정 시간 확인 시

[기대 결과]
TTS로 송출되는 도착 예정 시간과 Tmap 화면에 나오는 도착 예정 시간이 동일해야함

실제 TTS - 스타벅스 을지로국제빌딩점까지 222.8km 남았어요. 오후 2시 37분 도착 예정입니다.
Tmap 정보(좌측 하단 영역) - 오전 11시 30분 도착 예정

[문제 확인 시간]
2021.11.12 오전 11시 24분

[기타 참고사항]
Test 진행 영상 및 로그 첨부합니다.
[PBV01QA-193 (1).zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/7525061/PBV01QA-193.1.zip)

자체분석결과:
티맵에서 경유지에 대한 distance, total time 정보가 잘못들어옴
![image](https://user-images.githubusercontent.com/13480495/141413658-759f4390-d155-480e-b13c-92c8bcecf602.png)

**Comment by aqkhsg** [comment]
수정완료 했습니다. 배포 일정 잡히면 커멘트 달겠습니다.

**Comment by jhanulis7** [comment]
해당 경로로 정상 출력 확인
