### ISSUE TITLE
제주도 검색시 티맵 크래쉬

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#74]
![image](https://user-images.githubusercontent.com/13480495/142960945-b9728cc5-daeb-4aee-8bf1-430a3e4f5ef9.png)

[빌드 버전]

QA 0.5.3
[테스트 환경 정보]
Mobile - Device : AVN

[발생 빈도]
6/10

[이슈 현상]
거리가 먼 POI 목적지 설정 후 길 안내 시작하면서

[사전 조건]
1. EV Test Layer에서 Current Batterry RESET 설정

[재현 스텝]
1. "제주도" > 제주국제공항 목적지 선택

[기대 결과]
1. Tmap 앱이 종료되지 않고 길 안내가 시작되어야 함

[기타 참고사항]
로그 및 영상 첨부
[211122_1736.txt.zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/7585410/211122_1736.txt.zip)

**Comment by aqkhsg** [comment]
확인해보겠습니다.

**Comment by jhanulis7** [comment]
연관이슈 : #78

**Comment by aqkhsg** [comment]
0.6.5 버전에 수정 완료 되었습니다.
