### ISSUE TITLE
목적지까지 예상 배터리 부족시 충전소 제안 알림 발생 시 Tmap 앱이 팅기는 현상(ONE-Time)

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#75]
![image](https://user-images.githubusercontent.com/13480495/142961326-5a5603c7-559d-4b93-9201-60385e376a9b.png)

[빌드 버전]

QA 0.5.3
[테스트 환경 정보]
Mobile - Device : AVN

[발생 빈도]
ONE-Time

[이슈 현상]
목적지까지 예상 배터리 부족시 충전소 제안 알림 발생에서 Tmap 앱이 팅기는 현상

[사전 조건]
1. EV Test Layer에서 Current Batterry 0으로 설정

[재현 스텝]
1. 목적지 설정 후 충전소 제안 알림 확인

[문제 확인 시간}
2021.11.22 11: 38
2021.11.22 15 : 48

[기대 결과]
1. 앱이 종료 되면 안됨

[기타 참고사항]
로그 첨부 211122_1548.txt

[PBV01QA-213.zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/7585432/PBV01QA-213.zip)

**Comment by aqkhsg** [comment]
0.6.5 버전에 수정 완료 되었습니다.
