### ISSUE TITLE
발화로 목적지 설정 후에 Tmap 목적지 설정 UI가 나오면서 길 안내 시작이 되지 않는 현상

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#76]
![image](https://user-images.githubusercontent.com/13480495/142961690-f1884fde-d6b8-43fd-9b89-278541be2334.png)

[빌드 버전]

QA 0.5.3
[테스트 환경 정보]
Mobile - Device : AVN

[발생 빈도]
6/10

[이슈 현상]
VR 발화로 목적지 설정 한 후 Tmap 앱에서 목적지 길안내 설정 UI가 나오면서 길안내가 바로 되지 않는 현상

[사전 조건]

[재현 스텝]
1. "부산역으로 가자 발화" > 리스트 화면에서 첫 번째 목적지 선택

[기대 결과]
1. Tmap 앱에서 목적지 길안내 설정 UI가 나오지 않고 바로 길 안내 시작되어야 함

[기타 참고사항]
로그 및 영상 첨부

[PBV01QA-214.zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/7585449/PBV01QA-214.zip)

**Comment by aqkhsg** [comment]
이건 재현 시나리오가 혹시 있을까요?

**Comment by jhanulis7** [comment]
@aqkhsg 저도 해보았지만 재현이 안되어서요 영상과 로그로 판단해야 될거 같습니다.

**Comment by aqkhsg** [comment]
0.6.5 버전에 수정 완료 되었습니다.
