### ISSUE TITLE
티맵에서 아이콘 선택 지역 상세보기 노출 중 poi 발화 길 안내시 Tmap 팅김현상

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#77]
[빌드 버전]

VR 0.5.3
Tmap 0.6.3
[테스트 환경 정보]
Mobile - Device : Tablet

[발생 빈도]
1/10

[이슈 현상]
티맵에서 경복궁 아이콘 선택하여 상세보기 노출중 음성인식으로 "경복궁" 발화하여 목적지 설정 중 Tmap 팅김 현상 (AVN 에서는 10회 재현 시도 했지만 재현 안됨)

[사전 조건]
1. "국회의사당"으로 길 안내중
2. 현재 위치 : 서울특별시 중구 을지로

[재현 스텝]
1. 티맵에서 경복궁 아이콘 선택 > 경복궁 상세보기 팝업 노출중
2. 음성인식 > "경복궁" 발화 > 경복궁 리스트 발생 > "두번째" 발화

[기대 결과]
1. Tmap 팅기면 안됨

![image](https://user-images.githubusercontent.com/13480495/143021509-b8fcf157-b955-417c-bab9-001e3282409b.png)
[PBV01QA-220.zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/7587809/PBV01QA-220.zip)

**Comment by aqkhsg** [comment]
0.9.1 버전에서 수정되었습니다.
