### ISSUE TITLE
BT미디어 화면에서 POI 발화 길안내 시 Tmap 팅기는 현상

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#78]
[빌드 버전]

VR 0.5.3
Tmap 0.6.3
[테스트 환경 정보]
Mobile - Device : AVN

[발생 빈도]
10/10

[이슈 현상]
아이폰 1대 BT 연결한 후 BT 미디어 화면에서 음성인식 실행 하여 "서울역으로 가자" 발화 시 지도화면 진입하여 길안내 중 Tmap 팅기는 현상

[사전 조건]
1. 아이폰 1대만 BT 연결된 상태

[재현 스텝]
1. 미디어 화면 진입 > PTT 음성인식 버튼 > "서울역으로 가자" 발화 > 서울역 리스트에서 1번 선택

[기대 결과]
1. Tmap 팅기면 안됨

[기타 참고사항]
2021.11.23 16시25분 경 티맵 팅김 현상 발생

![image](https://user-images.githubusercontent.com/13480495/143021928-f1b53a56-cf04-4888-983d-de07b4a09c26.png)

**Comment by jhanulis7** [comment]
크래쉬 로그상 아래 이슈와 동일해보임
https://github.com/hkmc-airlab/pbv_client_tmap/issues/74

**Comment by aqkhsg** [comment]
0.6.5 버전에 수정 완료 되었습니다.
