### ISSUE TITLE
런처 화면에서 내비 관련 발화 후 내비 화면 발생한 후 앱 팅기는 현상. 

### ISSUE THREAD

**Issue by soorabang** [hkmc-airlab/pbv_client_tmap#79]
tmap version v0.6.5
재현 경로 :런처 >  "길안내해줘" > "어디로 갈까요"> "서울역" >"몇번째로 갈까요" (내비화면)  이때 앱이 튕김.
런처 > "서울역으로 가자" > 내비 화면 > 서울역 리스트 > 앱 튕김

100프로 재현은 아니고, 10번 중 2-3회 정도 재현이 됩니다. 
로그 첨부 드립니다 .
확인 부탁 드립니다.
[LogFilter_20211126_142810.txt.zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/7606586/LogFilter_20211126_142810.txt.zip)

![image](https://user-images.githubusercontent.com/77476356/143533673-8ddacc65-9ffa-40bc-a9aa-9c6ce68c49b2.png)
![image](https://user-images.githubusercontent.com/77476356/143533679-6473aacd-a105-43ae-938c-131486d468c7.png)

**Comment by soorabang** [comment]
재현 영상과 동일 시간대의 로그 함께 첨부 드립니다.
[20211126_150446.mp4.zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/7606637/20211126_150446.mp4.zip)
[LogFilter_20211126_150247.txt.zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/7606642/LogFilter_20211126_150247.txt.zip)

**Comment by aqkhsg** [comment]
0.9.1 버전에서 수정되었습니다.
