### ISSUE TITLE
티맵 네트웍 지연 팝업 > 타이머 완료후 > 잠시후 사용해주세요 이후 , VR 더이상 경로탐색중으로 동작안됨

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#84]
- 티맵 네트웍 지연 팝업 > 타이머 완료후 > 잠시후 사용해주세요 이후 , VR 더이상 경로탐색중으로 동작안됨

- 재현경로는 없고, 우연히 네트웍이 계속 안되는 티맵 현상이 있었음
- 경로 안내 종료후 정상 동작
   - 편한길로 안내해줘 했을때, 좀전에 티맵에서 네트웍 지연 팝업(타이머)  나오면서 잠시 후 다시 이용해주세요 라고 나왔는데요 , 이때 경로탐색중입니다. 라고 설정이 해제가 안되어서 계속 VR 에서 경로탐색중입니다라고 사용못하는 케이스가 있는거 같은데
- 재현이 어려워서 코드리뷰 요청드립니다.

**Comment by aqkhsg** [comment]
수정완료 하였고 다음 배포버전에서 확인부탁드립니다.

**Comment by jhanulis7** [comment]
네 재현이 잘 안되는 이슈이므로,
v0.11.1 이후 확인하도록 하겠습니다

![image](https://user-images.githubusercontent.com/13480495/146697287-c3f4a6f5-9004-4165-9544-e74385112300.png)

이슈 클로스 합니다.
