### ISSUE TITLE
currentDestination.isRouting : true 인데 (경로탐색중) linkLineString : “”  여서 서버 에러 발생

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#85]
currentDestination.isRouting : true 인데 (경로안내중)
linkLineString : “” 여서 저희 OPEN API 에러가 발생이 되고 있습니다. (1회성)
왜 linkLineString 가 없는지 확인 부탁드립니다. 로그 첨부드렸습니다.

![image](https://user-images.githubusercontent.com/13480495/146313449-9ec05438-f72c-429d-bc9e-93e74c888c3d.png)

<html>
<body>

193070 | 12-16 | 13:31:08.082 | E | 29749 | 29749 | [EDITH]EdithDataManager: |   | getNaviDestination: Destination(name=부산역[부산지하철1호선], address=부산 동구 중앙대로 200, totalDistance=1190833, totalTime=48764, longitude=129.03953474162526, latitude=35.115028822987576, tollFare=60200, poiId=151871, navSeq=null)
-- | -- | -- | -- | -- | -- | -- | -- | --

</body>
</html>�
[LogFilter_20211216_133128.txt.zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/7724798/LogFilter_20211216_133128.txt.zip)

**Comment by jhanulis7** [comment]
v0.11.1 for DV11

![image](https://user-images.githubusercontent.com/13480495/146697216-d5705734-9618-4ee6-a99c-ab54180438e3.png)

@aqkhsg  님, 
이건 수정된게 아니라 로그를 더 추가했다는거죠?

**Comment by aqkhsg** [comment]
네 우선 로그는 추가해놨고, 추가로 분석중입니다.

**Comment by jhanulis7** [comment]
이슈  클로스
