### ISSUE TITLE
[Navigation][기능] 특정지역(을지로) 길안내중 경유지 (전체)삭제 관련 발화 시 경유지 삭제 LIST가 사라지지않는 현상

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#86]
VR 0.6.1
Tmap 0.10.1
[테스트 환경 정보]
Mobile - Device : Tablet/AVN

[발생 빈도]
10/10

[이슈 현상]
특정지역(을지로)길 안내 중 경유지 삭제 LIST(경유지를 2개 이상 설정) 에서 경유지 (전체)삭제 관련 발화시 경유지가 전체 삭제되나 경유지 삭제 LIST는 유지되는현상
*전체 삭제가 아닌 1개 삭제시에는 정상동작함
*특정지역(을지로) 가 아닌 상태에서는 정상동작함

[사전 조건]
1."을지로" 목적지 설정 상태
2. 경유지 2개이상 설정상태

[재현 스텝]
1."경유지 삭제해줘" 발화
2. 경유지 삭제 LIST 상태에서 경유지 전체 삭제 발화

[기대 결과]
경유지 삭제 LIST 사라지고 재설정된 경로 보여줘야함

[기타 참고사항]
영상 ,로그 첨부합니다
로그(16시 34분 ~16시 38분)

**Comment by jhanulis7** [comment]
![image](https://user-images.githubusercontent.com/13480495/146471965-28197348-7be2-403f-ad14-567b51f411e5.png)


영상은 사이즈가 커서 슬랙으로 전달 드렸습니다,

**Comment by jhanulis7** [comment]
참고로
어제 저녁 짧게 테스트시,
navSeq 테스트앱으로 전달 주신 0.10.1.1. 버젼에서는 재현이 안되었고,
정식버젼 0.10.1 에서는 발생이 되었습니다.

**Comment by aqkhsg** [comment]
navSeq 테스트버전에 다른 내부이슈 수정사항이 들어있었는데요. 해당 수정으로 문제가 해결된것으로 보입니다.
오늘 수정내용 반영된 버전 정식 배포 예정입니다.

**Comment by jhanulis7** [comment]
재현경로 : 
v0.10.1.1 에서도 재현이 되었는데요
제가 확인해보니,  uninstall 후에 최초 실행하면 어떤 버젼이건 발생합니다.

앱삭제 > 동의 > 을지로 목적지 추가 > 잠실역 경유지 추가 > 역삼역 경유지  추가 > 경유지 삭제해줘 > 몇번째로? > 전체경유지 삭제 > onWayPointInfochage 안옴

**Comment by jhanulis7** [comment]
@aqkhsg 님,

해당 이슈 재현은 되어서 분석 진행중이실까요?

**Comment by aqkhsg** [comment]
이슈 확인 되서 수정 하였습니다만 0.11.1 버전에는 반영 못했네요.
다음 배포 버전에 반영예정입니다.

**Comment by jhanulis7** [comment]
아 아쉽네요 ㅠ ... 그래도 수정되었다고 하니 다행입니다.!
다음 배포때 이슈 클로스 하겠습니다.

**Comment by jhanulis7** [comment]
0.12.2  수정확인
