### ISSUE TITLE
[Navigation][기능] AA화면에서 PTT버튼 누르고 "우리집으로 가자" 발화시 Tmap 안내 패널도 같이 나오는 현상

### ISSUE THREAD

**Issue by soorabang** [hkmc-airlab/pbv_client_tmap#88]
[빌드 버전]

QA 0.6.2
Tmap - 0.11.1
[테스트 환경 정보]
Mobile - Device : AVN

[발생 빈도]
10/10

[이슈 현상]
AndroidAuto 화면에서 PTT버튼 눌러 VR 실행 후 "우리집으로 가자" 발화 후 Tmap에서 안내 패널이 나타나는 현상

[사전 조건]

AndroidAuto 연결
[재현 스텝]
1. PTT버튼 클릭 > 메인 메뉴화면 전환 > "우리집으로 가자" 발화 > Tmap 화면으로 전환 후 안내 시작

[기대 결과]
Tmap 안내 패널이 나오면 안됨

[기타 참고사항]
영상 첨부

 제가 장비로 테스트 했을 때는 AA 연결 상태와 무관하게, 
All menu 에서 "우리집 가자" 발화 시 재현이 되었습니다. 

https://user-images.githubusercontent.com/77476356/147017275-fa08bc50-a0b8-41a2-bdc8-df4c5a75bfeb.mp4

**Comment by aqkhsg** [comment]
Tmap 백그라운드 상태에서 VR '우리집 ' 발화시 Tmap 안내 패널 나타나는 현상 수정하였습니다.
12.24 배포에 적용

**Comment by soorabang** [comment]
DV12 차 바이너리 수정 확인.
