### ISSUE TITLE
[Navigation][기능] 경유지 2개 추가된 상태에서 임의 목적지 발화 시 Tmap 튕기는 현상

### ISSUE THREAD

**Issue by soorabang** [hkmc-airlab/pbv_client_tmap#91]
내부  QA 에서 나온 이슈로,  Tablet 에서 확인시에도 100% 재현되고 있습니다. 
확인 부탁 드립니다. 
![image](https://user-images.githubusercontent.com/77476356/147423919-8db1b31a-decb-4e1c-badd-d3bcad494fa6.png)

[빌드 버전]

VR 0.7.0
Tmap 0.11.1
[테스트 환경 정보]
Mobile - Device : AVN/Tablet

[발생 빈도]
10/10

재현시간 : 18:17

[이슈 현상]
경유지 2개 추가된 상태에서 임의 목적지 발화 시 Tmap 튕기는 현상

[사전 조건]
경로 안내 중인 상태

[재현 스텝]
경유지 2개 추가 > 임의 목적지 발화

[기대 결과]
Tmap 튕기면 안됨

**Comment by soorabang** [comment]
0.12.2 버전에서는 재현이 안되는데, 수정 사항 포함된 것인지 확인 부탁 드립니다.

**Comment by jhanulis7** [comment]
이건 필드에서 수정되거나 리포트 된걸로 보고 이슈 클로스 함
