### ISSUE TITLE
[Navigation] 경로탐색중입니다. 잠시만 기다려주세요 requestRouteOn 타이밍 수정요청

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#94]
- VR 에서 해당 state table. 을 ASR 완료후에 위치를 바꾸게 되면, 
  - 해당 db update 가 비동기로 오래걸리기때문에 성능상의 이슈(VR Server Response 타임에 영향)
  - DB 업데이트 후 서버에 컨텍스트 전달 sdk. 구조 로직 변경
 
위와 같은 이슈로 어려움이 좀 있는데요,
저 해당 필드를 좀 타이트하게 경탐중 여부를 판단해주시면 안될까요?

**Comment by aqkhsg** [comment]
우택님께서 db읽는 시간을 최대한 뒤로 미뤄서 테스트해봐주신다고 했는데,
그렇게 하기가 어려운걸까요?
지금도 가능한 최대한 타이트하게 잡은걸로 알고있는데 다시 한번 확인은 해볼게요

**Comment by jhanulis7** [comment]
@aqkhsg 님

2가지 사항 검토 부탁드립니다.
- db를 늦게 읽는건 테스트를 해보았지만 ASR Response Time 이 (NaviState 블로킹 delay 300ms : 태블릿기준) DB. 읽는 시간을 기다리고 서버에 전달해야 해서, 성능상의 이슈가 큼
  - 1번 ) NaviState 에 필드를 보면 db 와 상관없는 것들 같은데, db query 하는 필드가 있나요? 혹시 isRequestRouteOn 에 해당하는 필드가 빨리 response 를 전달할수 있는지 확인 부탁드립니다. 즉 요것만 따로 call 하면 어떨까해서요..
-  2번)저희가 경탐중에 또 경탐을 내리면 reqErrror 로 callback 을 전달해주실수 있을까요?

이것저것 검토해보고 있는데요, 저 2개가 되는지 검토 해주시면 또 나름 고민해보겠습니다.

**Comment by aqkhsg** [comment]
@jhanulis7 님
navistate에 trafficStatus 내용을 만들때 시간이 좀 걸리고 있습니다.
requestRouteOn만 따로 빼려는 이유는 naviState table 값 가져오는 시간이 오래걸려서 따로 빼려는 게 맞나요? 

2) 번은  isRequestRouteOn 로 그때 처리를 하신다고 들은거 같은데, isRequestRouteOn를 대신해서  2) 방식으로 처리를 바꾸려는 의도실까요?

**Comment by jhanulis7** [comment]
1, 네 맞습니다. requestRouteOn 만 빼면 delay 없이 바로 가져올수 있지 않을까의 접근 방법이구요

> 2)는 isRequestRouteOn 필드로 처리를 하신다고 들은거 같은데, isRequestRouteOn를 대신해서 2) 방식으로 처리를 바꾸려는 의도실까요?
네 맞습니다 일단 티맵에 req 보내고 나서 답변 받고 dm 전달해서 결과 받으면 늦게 판단이 될수 있어서...

**Comment by aqkhsg** [comment]
1)은 테스트버전 전달드려볼게요. 
![image](https://user-images.githubusercontent.com/42509008/150934041-6cbaa882-1421-438c-b831-8af47bef9898.png)

2)는 티맵 기본 구조가 터치만 고려해서 만들어진터라.. 현재 구조상 reqRoute가 또 오면 꼬일수가 있을거같아요. 얘기하신 내용은 반영이 어려워보입니다.
