### ISSUE TITLE
안내종료 > 경유지가 DB 에 계속 남아서 VR 로 전달 됨

### ISSUE THREAD

**Issue by jhanulis7** [hkmc-airlab/pbv_client_tmap#96]
이슈) [Navigation][기능] 충전소 제안으로 경유지 설정 > 안내종료 > 충전소 제안으로 목적지 설정 시 위치 중복 Fallback 발생

서울역 목적지 > SOC 제안, 충전소 경유지 추가 > 안내종료 > SOC 제안 > 목적지 중복 발생
 - 원인 ) 안내 종료에 따라서 목적지는 DB 에 null 로 전달 받으나, 경유지는 지워지지 않고 경유지를 전달 함.
 - 해결 ) 안내 종료시 DB 경유지도 삭제 되어야 함
![image](https://user-images.githubusercontent.com/13480495/152994534-6fac370d-f935-4fae-97aa-9968069502ce.png)

[빌드 버전]
-VR 0.7.6
-Tmap 0.15.5

[테스트 환경 정보]
Mobile - Device : AVN / Tablet 모두 발생

[발생 빈도]
10/10

[이슈 현상]
배터리 부족 알럿으로 충전소제안 경유지 설정 > 안내 종료 > 다시 알럿 발생 충전소 제안으로 목적지 설정 시 위치 중복 Fallbaack 발생

[사전 조건]
1. 길 안내 중

[재현 스텝]
1. PTTbutton앱에서 배터리 부족 알럿 발생 버튼 선택 > 근처 충전소 경유지로 추가
2. PTT > "안내 종료" 발화로 안내 종료
3.PTTbutton앱에서 배터리 부족 알럿 발생 버튼 선택 > 그래 아니 화면에서 '그래' 선택 또는 발화 > 중복 위치 Fallback 발생

[기대 결과]
1. 위치 중복 Fallback이 발생하지 않고 충전소로 목적지가 설정 되어야 함

[기타 참고사항]
로그 및 영상 첨부
[PBV01QA-387.zip](https://github.com/hkmc-airlab/pbv_client_tmap/files/8024088/PBV01QA-387.zip)

**Comment by aqkhsg** [comment]
2.10 배포에 수정예정입니다.
